#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH=$PATH:/usr/local/share/git-core/contrib/diff-highlight
export PATH=/usr/local/bin:$PATH
export PATH=${HOME}/bin:$PATH
export PATH=/Applications/PyCharm.app/Contents/MacOS:${PATH}
#export LC_ALL=ja_JP.UTF-8
export LC_ALL=en_US.UTF-8

if [[ -f /usr/local/bin/gls ]]; then
  alias ls='gls --group-directories-first -F --color=auto'
fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f /Users/igawa/google-cloud-sdk/path.zsh.inc ]; then
  source '/Users/igawa/google-cloud-sdk/path.zsh.inc'
fi

# The next line enables shell command completion for gcloud.
if [ -f /Users/igawa/google-cloud-sdk/completion.zsh.inc ]; then
  source '/Users/igawa/google-cloud-sdk/completion.zsh.inc'
fi

export VIRTUALENVWRAPPER_PYTHON=`which python`
export VIRTUALENVWRAPPER_VIRTUALENV=`which virtualenv`

source `which virtualenvwrapper.sh`
export WORKON_HOME=~/.virtualenvs
