#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH=$PATH:/usr/local/share/git-core/contrib/diff-highlight
export PATH=/usr/local/bin:$PATH
export PATH=${HOME}/bin:$PATH
export PATH=${HOME}/.linuxbrew/bin:$PATH
export PATH=${HOME}/.local/bin:$PATH
export PATH=/snap/bin:$PATH
#export LC_ALL=ja_JP.UTF-8
export LC_ALL=en_US.UTF-8

if [[ -f /usr/local/bin/gls ]]; then
  alias ls='gls --group-directories-first -F --color=auto'
fi

# alias for open command
if [ -f /usr/bin/xdg-open ]; then
  alias open=xdg-open
fi

# alias for zypper update command
if [ -f /usr/bin/zypper ]; then
  alias zu='sudo zypper update -y --auto-agree-with-licenses'
  alias zi='sudo zypper install -y --auto-agree-with-licenses'
  alias zs='sudo zypper search'
fi

alias emacs='emacsclient -nw -a ""'
alias chrome='google-chrome'
export EDITOR='emacs -nw'
export VISUAL='${EDITOR}'
export SUDO_PROMPT='[sudo] %p 🔒: '

# The next line updates PATH for the Google Cloud SDK.
if [ -f /Users/igawa/google-cloud-sdk/path.zsh.inc ]; then
  source '/Users/igawa/google-cloud-sdk/path.zsh.inc'
fi

# The next line enables shell command completion for gcloud.
if [ -f /Users/igawa/google-cloud-sdk/completion.zsh.inc ]; then
  source '/Users/igawa/google-cloud-sdk/completion.zsh.inc'
fi

export VIRTUALENVWRAPPER_PYTHON=`which python`
export VIRTUALENVWRAPPER_VIRTUALENV=`which virtualenv`

source `which virtualenvwrapper.sh`
export WORKON_HOME=~/.virtualenvs

if [ -z "$SSH_AUTH_SOCK" ] ; then
    eval `ssh-agent`
    ssh-add
fi

# ssh-add -l > /dev/null 2>&1
# if [ $? -ne 0 ]; then
#   ssh-add
# fi

PATH="/home/masayuki/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/masayuki/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/masayuki/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/masayuki/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/masayuki/perl5"; export PERL_MM_OPT;

# added by travis gem
[ -f /home/masayuki/.travis/travis.sh ] && source /home/masayuki/.travis/travis.sh
